bookReviews/apps/LoginAndRegistration/urls.py
from django.conf.urls import url
from .import views


urlpatterns=[
    url(r'^$',views.register,name='registration'),
    url(r'^create/$',views.create,name='create'),
    url(r'^login/$',views.login,name='login'),
    url(r'^loginProccess',views.proccess,name='proccess'),
    url(r'^logoff',views.logoff,name='logoff')


]

bookReviews/apps/bookReviewer/urls.py
from django.conf.urls import url
from .import views


urlpatterns=[
    url(r'^book/$',views.dashboard,name='dashboard'),
    url(r'^create/$',views.create,name='create'),
    url(r'^books/(?P<book_id>\d+)$',views.bookProfile,name='bookProfile'),
    url(r'^users/(?P<user_id>\d+)$',views.userProfile,name='userProfile'),
    url(r'^add_review/(?P<book_id>\d+)$',views.addReview,name='addReview'),
    url(r'^delete_review/(?P<review_id>\d+)/(?P<book_id>\d+)$',views.deleteReview,name='deleteReview')

]

bookReviews/bookReviews/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/',include('apps.bookReviewer.urls', namespace='books')),
    url(r'^',include('apps.LoginAndRegistration.urls', namespace='userLG'))
    
]

bookReviews/apps/bookReviewer/models.py
from django.db import models

from ..LoginAndRegistration.models import User

# Create your models here.


class BookManager(models.Manager):
    def bookValidator(self,form,user_id):
        error=[]
        # book title
        if len(form['bookTitle'])<1:
            error.append("bookTitle cannot be blank!!")
        if len(form['bookTitle'])<5:
            error.append("First name should be atleat 5 characters")

        # author name
        if len(form["typeAuthor"])<1:
            if len(form["author"])<1:
                error.append("Please provide an author name")
            else:
                author_name=form["author"]
        else:
            if form["author"]:
                error.append("Please include only one Author")
            else:
                if len(form["typeAuthor"])<1:
                    error.append("Please provide an author name")
                elif len(form["typeAuthor"])<5:
                    error.append("author name should be atleast 4 characters")
                else:
                    author_name=form["typeAuthor"]
                    
        # reviews
        if len(form["review"])<1:
            error.append("Please provide a review")
        if len(form["review"])<5:
            error.append("review should be atleast 5 characters")

        # rating
        if len(form["rating"])<1:
            error.append("Please provide a rating")
    
        if error:
            return(False,error)
        else:
            book=Book.objects.create(user=User.objects.get(id=user_id), title=form["bookTitle"],author=author_name)
            Review.objects.create(user=User.objects.get(id=user_id),book=Book.objects.get(id=book.id),review=form["review"],rating=form["rating"])
            return(True,error,book.id)
    
    def AddReviews_validator(self,form,book_id,user_id):
        error=[]
          # reviews
        if len(form["review"])<1:
            error.append("Please provide a review")
        if len(form["review"])<3:
            error.append("review should be atleast 3 characters")

        # rating
        if len(form["rating"])<1:
            error.append("Please provide a rating")
    
        if error:
            return(error)
        else:
            Review.objects.create(user=User.objects.get(id=user_id),book=Book.objects.get(id=book_id),review=form["review"],rating=form["rating"])
            return(error)


class Book(models.Model):
    title=models.CharField(max_length=255)
    author=models.CharField(max_length=255)
    objects=BookManager()
    user=models.ForeignKey(User,related_name="book")

    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
  
class Review(models.Model):
    review=models.TextField()
    rating=models.IntegerField()
    user=models.ForeignKey(User,related_name="review")
    book=models.ForeignKey(Book,related_name="book_reviews")
    objects=BookManager()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

bookReviews/apps/bookReviewer/views.py
from django.shortcuts import render,redirect
from django.core.urlresolvers import reverse
from django.contrib import messages

from .models import Book,Review
from ..LoginAndRegistration.models import User

def dashboard(request):

    if "user_id" not in request.session:
        return redirect(reverse("userLG:login"))

    if "color" not in request.session:
        request.session["color"]="success"
    
    books=Book.objects.all().order_by("-created_at")
    valid_book_list=[]

    for index in books:
       if index.book_reviews.last():
            review=index.book_reviews.last().review
            if len(review)>1:
                valid_book_list.append(index)
          


    context={
        'books':valid_book_list,
        'user':User.objects.get(id=request.session["user_id"]).first_name
    }
    
    return render(request,"bookreviewer/dashboard.html",context)


# create book and reviews
def create(request):
    if request.method == "GET":
        return redirect(reverse("userLG:login"))
    if "user_id" not in request.session:
        return redirect(reverse("userLG:login"))

    valid,response,book_id=Book.objects.bookValidator(request.POST,request.session["user_id"])

    if valid==False:
        request.session["color"]="danger"
        for error in response:
            messages.error(request, error)
    else:
        print("successfully created BOOK")
        request.session["color"]="success"
        messages.success(request, " Book Review Successfully Created")

    return redirect(reverse("books:bookProfile" ,kwargs={'book_id':book_id }))

    



def bookProfile(request,book_id):
    if "user_id" not in request.session:
        return redirect(reverse("userLG:login"))

    context={
        'book':Book.objects.get(id=book_id)
    }

    return render(request,"bookreviewer/book_profile.html",context)



def userProfile(request,user_id):
    try:
        request.session["user_id"]
    except KeyError:
        print("TryAndExcept <<<<<<-------")
        return redirect(reverse("userLG:login"))

    if request.session["user_id"] is not int(user_id):
        print("if <<<<<<-------")
        return redirect(reverse("userLG:login"))

   
    review_list=[]
    for index in Review.objects.raw("SELECT * FROM bookReviewer_review WHERE user_id ="+user_id+"  GROUP BY book_id"):

        review_list.append(index)

    context={
        'user':User.objects.get(id=user_id),
        'book_reviewed':review_list
    }
    
    return render(request,"bookreviewer/user_profile.html",context)
    

def deleteReview(request,review_id,book_id):

    if request.method == "GET":
        return redirect(reverse("userLG:login"))


    Review.objects.get(id=review_id).delete()

    return redirect(reverse("books:bookProfile",kwargs={'book_id':book_id }))

def addReview(request,book_id):
    if request.method == "GET":
        return redirect(reverse("userLG:login"))

    error=Review.objects.AddReviews_validator(form=request.POST,book_id=book_id,user_id=request.session["user_id"])

    if len(error)<1:
        request.session["color"]="danger"
        for error in error:
            messages.error(request, error)

    else:
        request.session["color"]="success"
        messages.success(request, "Review Successfully Created")

    return redirect(reverse("books:bookProfile",kwargs={'book_id':book_id }))

bookReviews/apps/bookReviewer/templates/bookreviewer/book_profile.html
{%extends "bookreviewer/layout.html"%}


{%block content%}
    <header class="blog-header py-3 bg-dark">

        <div class="text-right">
            <a class="btn btn-sm btn-outline-info ml-2 mr-2" href="{%url 'books:dashboard'%}">Dashboard</a>
            <a class="btn btn-sm btn-outline-danger ml-2 mr-3" href="{%url 'userLG:logoff'%}">Log out</a>
        </div>

    </header>
    <div class="bookcontainer container mt-5">
        <div class="bg-dark text-white py-3 pl-2 text-center shadow">
            <h5>{{book.title}}</h5>
            <small class="font-weight-light">Author: {{book.author}}</small>
        </div>
        <div class="mt-5 reviewSection">
            <div class="row">
                <h6 class="col-10">Reviews:</h6>
                <button class="btn btn-outline-dark btn-sm " id="addReview"> Add Review</button>
            </div>
            <hr>
            <div class="reviewForm">
                <form action="{%url 'books:addReview' book_id=book.id%}" method="post">
                    {% csrf_token %}
                    <div class="form-group ">
                        <label for="review">Review</label>
                        <textarea class="form-control col-7" name="review" id="review" rows="3"></textarea>
                    </div>
                    <div>
                        <label for="rating"> Rating:</label>
                        <select id="rating" name="rating">
                            <option value="" selected>Choose...</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                        </select>
                    </div>

                    <div class="text-right">
                        <button class="btn btn-outline-success btn-sm shadow " type="submit">Submit Review</button>
                    </div>
                </form>
                <hr class="mb-4">
            </div>





            <div class="">
                {% for index in book.book_reviews.all reversed%}
                    <div class="ml-3">
                        <form action="{%url 'books:deleteReview' review_id=index.id book_id=book.id%}" method="post">
                            {% csrf_token %}
                            <small>Rating: {{index.rating}}</small>
                            <p class="font-weight-light mb-0"><a href="{%url 'books:userProfile' user_id=index.user_id%}"> {{index.user.first_name}}</a> says: {{index.review}}</p>
                            <small>Posted on {{index.created_at}}</small> 
                            {% ifequal request.session.user_id index.user_id %}
                                <small><button type="submit" class="ml-5 btn btn-sm btn-outline-secondary">Delete this Review </button></small> 
                            {% endifequal %}
                           
                        </form>
                    </div>
                    <hr>
                {% endfor %}
            
            </div>
        </div>
    </div>



{%endblock content%}

bookReviews/apps/bookReviewer/templates/bookreviewer/dashboard.html
{%extends "bookreviewer/layout.html"%}
<title>Books Home</title>
   
{%block content%}

    <header class="blog-header py-3 bg-dark">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1 ml-5">
                <h4 class="text-white"> <i class="fas fa-book-reader mr-2"></i>Welcome, {{user}} </h4>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
                <a class="btn btn btn-outline-primary ml-2 mr-3" href="{%url 'books:userProfile' user_id=request.session.user_id%}"><i class="fas fa-user-circle"></i></a>
                <button  data-toggle="modal" data-target="#createButton" class="btn btn-sm btn-outline-warning">Add Book and Review</button>
                <a class="btn btn-sm btn-outline-danger ml-2 mr-3" href="{%url 'userLG:logoff'%}">Log out</a>
            </div>
        </div>
    </header>

    <div class="container">

       
       <div class="row">
            <div class="leftSection col-7 mt-5">
                {% if messages %}
                    <ul class="messages list-inline text-{{request.session.color}}">
                    {% for message in messages %}
                        <li{% if message.tags %} class="ml-4 {{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                    </ul>
                {% endif %}
                <div>
                    <h6 class="bg-info p-2 text-white shadow">Recent Book Reviews:</h6>
                    <hr>

                    {% for index in books  %}

                        {% if forloop.counter < 4 %}
                            <div>
                                <h6><a href="{%url 'books:bookProfile' book_id=index.id%}">{{index.title}}</a></h6>
                                <small class="ml-2">Rating: {{index.book_reviews.last.rating}} <i class="fas fa-star"></i></small>
                                <p class="ml-2 font-weight-light mb-0"><a href="{%url 'books:userProfile' user_id=index.user_id%}">{{index.book_reviews.last.user.first_name}}</a> says: {{index.book_reviews.last.review}}</p>
                                <small class="ml-2"> Posted on the {{index.book_reviews.last.created_at}}</small>
                                <hr>
                            </div>
                        {% endif %}

                    {% endfor %}
                    
                </div>
            </div>

            <div class="rightSection col-5 mt-5">
                <h6>Other Books with Reviews:</h6>
                <div class="otherbooks border border-info rounded ">
                    <ul class="booklinks">
                        {% for index in books  %}
                            <li><a href="{%url 'books:bookProfile' book_id=index.id%}">{{index.title}}</a></li>
                        {% endfor %}
                        
                        

                    </ul>
                </div>
            
            </div>
       </div>

        <!-- Modal -->
        <div class="modal fade" id="createButton" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header ">
                        <div class="modalHeader text-center">
                            <h5>Add Book and Reviews</h5>
                        </div>
                        <button type="button" class="close closebutton ml-1" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="">

                            <form class="needs-validation" action="{%url 'books:create'%}" method="post">
                                {% csrf_token %}
    
                                <div class="mb-3">
                                    <label for="firstName">Book Title:</label>
                                    <input type="text" class="form-control " id="bookTitle" name="bookTitle" value="" placeholder="Title">
                                </div>
                                <div class="mb-3">
                                    <h6>Author:</h6>
                                    <div class="input-group mb-3 ml-2">
                                        <div class="input-group-prepend">
                                            <label class="input-group-text" for="author">Author</label>
                                        </div>
                                        <select class="custom-select" id="author" name="author">
                                            <option value="" selected>Choose...</option>
                                            <option value="Aaron Dasani">Aaron Dasani</option>
                                            <option value="Lavinia Smith">Lavinia Smith</option>
                                            <option value="Jake Burn">Jake Burn</option>
                                        </select>   
                                    </div>
                                    <small class="ml-3"> Or add a new author:</small>
                                    <input type="text" class="form-control ml-2" name="typeAuthor" placeholder="Author name">
                                
        
                                </div>
    
                                <div class="form-group">
                                    <label for="review">Review</label>
                                    <textarea class="form-control" name="review" id="review" rows="3"></textarea>
                                </div>
                                <div>
                                    <label for="rating"> Rating:</label>
                                    <select id="rating" name="rating">
                                        <option value="" selected>Choose...</option>
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                    </select>
                                </div>

                                <hr class="mb-4">
                                <!-- <input type="hidden" name="editRequest" id="user_id" value="fromUser"> -->
                                <div class="text-right">
                                    <button class="btn btn-warning shadow" type="submit">Add Book and Review</button>
                                </div>
                            </form>
                        </div>
    
                    </div>

                </div>
            </div>
        </div>
            
    </div>


{%endblock content%}

bookReviews/apps/bookReviewer/templates/bookreviewer/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Books Home</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {%load static%}
    <link rel="stylesheet" href="{%static 'bookreviewer/css/stylesheet.css'%}">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{%static 'bookreviewer/script/jquery.js'%}"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
</head>
<body>

    {%block content%}{%endblock%}










    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/scrollreveal"></script>
</body>
</html>

bookReviews/apps/bookReviewer/templates/bookreviewer/user_profile.html
{%extends "bookreviewer/layout.html"%}


{%block content%}
    {%load static%}
    <header class="blog-header py-3 bg-dark">

        <div class="text-right">
            <a class="btn btn-sm btn-outline-info ml-2 mr-3" href="{%url 'books:dashboard'%}">Dashboard</a>
            <button  data-toggle="modal" data-target="#createButton" class="btn btn-sm btn-outline-warning">Add Book and Review</button>
            <a class="btn btn-sm btn-outline-danger ml-2 mr-3" href="{%url 'userLG:logoff'%}">Log out</a>
        </div>

    </header>

    <div class="container mt-5">

        <div class="text-white shadow p-3 row usercontainer" style="background-image:url({%static 'bookreviewer/image/book.jpeg'%})">
            <div class="col-4 mt-4"> 
                <img class="rounded-circle mb-3 shadow-lg" src="{%static 'bookreviewer/image/funnyPic.jpg'%}" alt="profile picture" width="120px" height="110px">
                <h6>{{user.first_name}} {{user.last_name}}</h6>
                <h6><i class="fas fa-at mr-1"></i>{{user.email}}</h6>
                <h6 class="text-warning">Total Reviews: {{user.review.count}}</h6>
            </div>
            <h2 class="col-4 text-center mt-4 ">Hello <small>{{user.nickname}} !!</small></h2>

        </div>

        <div class="mt-5">
            <h5 class="bg-dark p-2 text-white">Posted Reviews on the following books:</h5>
            <ul>
                {% for index in book_reviewed %}
         
                    <li><i class="fas fa-book mr-2"></i><a href="{%url 'books:bookProfile' book_id=index.book.id%}" class="text-dark">{{index.book.title}}</a></li>
                {% endfor %}
                
            </ul>

        </div>



        <!-- Modal -->
        <div class="modal fade" id="createButton" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header ">
                        <div class="modalHeader text-center">
                            <h5>Add Book and Reviews</h5>
                        </div>
                        <button type="button" class="close closebutton ml-1" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="">

                            <form class="needs-validation" action="{%url 'books:create'%}" method="post">
                                {% csrf_token %}

                                <div class="mb-3">
                                    <label for="firstName">Book Title:</label>
                                    <input type="text" class="form-control " id="bookTitle" name="bookTitle" value="" placeholder="Title">
                                </div>
                                <div class="mb-3">
                                    <h6>Author:</h6>
                                    <div class="input-group mb-3 ml-2">
                                        <div class="input-group-prepend">
                                            <label class="input-group-text" for="author">Author</label>
                                        </div>
                                        <select class="custom-select" id="author" name="author">
                                            <option value="" selected>Choose...</option>
                                            <option value="Aaron Dasani">Aaron Dasani</option>
                                            <option value="Lavinia Smith">Lavinia Smith</option>
                                            <option value="Jake Burn">Jake Burn</option>
                                        </select>   
                                    </div>
                                    <small class="ml-3"> Or add a new author:</small>
                                    <input type="text" class="form-control ml-2" name="typeAuthor" placeholder="Author name">
                                
        
                                </div>

                                <div class="form-group">
                                    <label for="review">Review</label>
                                    <textarea class="form-control" name="review" id="review" rows="3"></textarea>
                                </div>
                                <div>
                                    <label for="rating"> Rating:</label>
                                    <select id="rating" name="rating">
                                        <option value="" selected>Choose...</option>
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                    </select>
                                </div>

                                <hr class="mb-4">
                                <div class="text-right">
                                    <button class="btn btn-warning shadow" type="submit">Add Book and Review</button>
                                </div>
                            </form>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>


{%endblock content%}