Ecommerce/Ecommerce/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include("apps.dashboard.urls", namespace="dashboard")),
    url(r'^adminDashboard/', include("apps.AdminDashboard.urls", namespace="adminDashboard")),
    url(r'^', include("apps.LoginAndRegister.urls", namespace="userLG"))


]

Ecommerce/apps/AdminDashboard/urls.py
from django.conf.urls import url
from .import views
from django.conf import settings
from django.conf.urls.static import static


app_name='AdminDashboard'

urlpatterns=[
    url(r'^$',views.admin, name='admin'),
    url(r'^searchOrders/$',views.searchOrders, name='searchOrders'),
    url(r'^viewProduct/(?P<order_id>\w+)$',views.viewProduct, name='viewProduct'),
    url(r'^in_stock/$',views.productsInStock, name='productsInStock'),
    url(r'^searchProduct/$',views.searchProduct, name='searchProduct'),
    url(r'^create/$',views.create, name='create'),
    url(r'^delete/$',views.delete, name='delete'),
    url(r'^edit/$',views.edit, name='edit'),
    url(r'^fetchProductInfo/$',views.fetchProductInfo, name='fetchProductInfo'),


    url(r'^change_paged/$',views.ajax_pagination, name='ajax_pagination')
 

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommerce/apps/LoginAndRegister/urls.py
from django.conf.urls import url
from .import views

app_name='LoginAndRegister'

urlpatterns=[
    url(r'^$',views.home,name='home'),
    url(r'^register/$',views.register,name='registration'),
    url(r'^create/$',views.create,name='create'),
    url(r'^login/$',views.login,name='login'),
    url(r'^loginProccess',views.proccess,name='proccess'),
    url(r'^logoff',views.logoff,name='logoff')


]

Ecommerce/apps/dashboard/urls.py
from django.conf.urls import url
from .import views

app_name='dashboard'

urlpatterns=[
    url(r'^$',views.dashboard, name='dashboard'),
    url(r'^product/(?P<product_id>\w+)/(?P<product_brand>\w+)$',views.product_page, name='product_page'),
    url(r'^checkout/$',views.checkout, name='checkout'),
    url(r'^thankYou/$',views.thankYou, name='thankYou'),
    url(r'^payementProcess/$',views.payementProcess, name='payementProcess'),
    url(r'^add_to_cart$',views.add_to_cart, name='add_to_cart'),
    url(r'^PriceRange/$',views.PriceRange, name='PriceRange'),
    url(r'^searchProduct/(?P<category>\w+)$',views.searchProduct, name='searchProduct'),
    url(r'^searchBrand/$',views.searchBrand, name='searchBrand')


    

]

Ecommerce/apps/dashboard/models.py
from django.db import models

from ..LoginAndRegister.models import User
# Create your models here.



class Cart(models.Model):
    product_id=models.CharField(max_length=80)
    brand=models.CharField(max_length=40)
    itemName=models.CharField(max_length=255)
    price=models.FloatField()
    quantity=models.IntegerField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    user=models.ForeignKey(User,related_name='cart',on_delete=models.DO_NOTHING)

class Order(models.Model):
    order_id=models.CharField(max_length=80)
    brand=models.CharField(max_length=40)
    itemName=models.CharField(max_length=255)
    price=models.FloatField()
    quantity=models.IntegerField()
    totalCost=models.FloatField()
    OrderStatus=models.CharField(max_length=40)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    user=models.ForeignKey(User,related_name='order',on_delete=models.DO_NOTHING)

Ecommerce/apps/dashboard/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.urls import reverse
from django.contrib import messages
from django.http import JsonResponse
import random
import string
# Create your views here.
from .models import Cart,Order
from..LoginAndRegister.models import User
import webhoseio
webhoseio.config(token='ba97ec58-a132-4dad-aa67-28e170c1c0d6')      
def dashboard(request):

    # check if their is a user_id, basically checking if a user is logged in
    if 'user_id' not in request.session:
        return redirect(reverse("userLG:login"))

    # remember some information about the search history
    if 'productInfo' not in request.session:
        request.session['productInfo']={
            'categories':'shirt',
            'price':'60',
            'brand':'nike'
        }

    # those information was used to help the user be able to click on the suggestion product and be able to show the correct information about that specific product. We delete it here becuase we do not need it in this page.
    if "product" in request.session:
        del request.session["product"]
        del request.session['product_id']
        request.session.modified = True

    # miscelleneous information to make the dashboard page better
    itemsInCart=Cart.objects.all().count()
    userLevel=User.objects.get(id=request.session['user_id']).user_level
    
    # sending an API request through the 'sendingRequest' function. THe response will be some product Data
    product_list=sendingRequest(request, catergories=request.session['productInfo']['categories'])
    
    return render(request,"ecommerce/dashboard.html", {'product_list':product_list,'itemsInCart':itemsInCart,'user_level':userLevel} )
    # return render(request,"ecommerce/dashboard.html",{'itemsInCart':itemsInCart,'user_level':userLevel})



def product_page(request,product_id,product_brand):
    if 'user_id' not in request.session:
        return redirect(reverse("userLG:login"))

    product_list={}

    if 'product_id' not in request.session:
        print("product_id Initialized <<<<<<<-------")
        request.session['product_id']=None
 
    if request.session['product_id'] != str(product_id) or 'product' not in request.session:
        request.session['product_id']=product_id
       
        print("data from request <<<<<-------")
        query_params = {
            "q": "product_id: "+product_id+"",
            'size':'1'
        }
    
        output = webhoseio.query("productFilter", query_params)
        product_list={
            'product_name':output['products'][0]['name'],
            'product_brand':output['products'][0]['brand'],
            'product_price':output['products'][0]['price'],
            'product_image':output['products'][0]['images'][0],
            'product_description':output['products'][0]['description']
            
        }
        request.session['product']=product_list
        # Get the next batch of products
        output = webhoseio.get_next()

        # changing the brand filter in the session
        request.session['productInfo']['brand']=product_brand
        request.session.modified = True

        suggestion_list=sendingRequest(request,catergories=request.session['productInfo']['categories'],brand=product_brand,product_id=product_id)
        request.session["suggested_product"]=suggestion_list
    else:
        print("data from session <<<<<-------")
        product_list=request.session['product']
        suggestion_list= request.session["suggested_product"]

    itemsInCart=Cart.objects.all().count()
    
    return render(request,"ecommerce/productPage.html",{'product_list':product_list,'suggested_product':suggestion_list,'itemsInCart':itemsInCart})




def checkout(request):
    cart=Cart.objects.all()
    totalCost=0
    discount=10
    for index in cart:
        price=index.price*index.quantity
        totalCost+=price


    context={
        'products':cart,
        'totalCost':totalCost-discount,
        'discount':discount,
        'totalItems':Cart.objects.all().count()
    }
    
    return render(request,"ecommerce/checkout.html",context)


def payementProcess(request):
    # Save Order
    print(request.POST)
    try:
        current_user=request.session['user_id']
    except:
        return redirect(reverse("userLG:login"))

    cart=Cart.objects.filter(user_id=request.session['user_id'])
    order_id=''.join(random.choices(string.ascii_uppercase + string.digits, k=10))
    print(">>>>>>>>>>>>>>>" ,order_id)

    for index in cart:
        Order.objects.create(
            user=User.objects.get(id=current_user),
            order_id=order_id,
            brand=index.brand,
            itemName=index.itemName,
            price=index.price,
            quantity=index.quantity,
            totalCost=(index.price) * (index.quantity),
            OrderStatus='Order In'
        )

    # Delete Cart Items after purchase is done
    Cart.objects.filter(user_id=request.session['user_id']).delete()


    return redirect(reverse("dashboard:thankYou"))


def thankYou(request):
    context={
       'user':User.objects.get(id=request.session['user_id']).first_name
    }
    return render(request,"ecommerce/thankYou.html",context)



def add_to_cart(request):
    print(request.POST)
    try:
        current_user=request.session['user_id']
    except:
        return redirect(reverse("userLG:login"))

    Cart.objects.create(user=User.objects.get(id=current_user),product_id=request.session['product_id'],brand=request.POST['brand'],itemName=request.POST['productName'],price=request.POST['price'],quantity=request.POST['quantity'])

    ItemsInCart=Cart.objects.all().count()
    return JsonResponse({'numberOfItems': ItemsInCart})





def PriceRange(request):
    request.session['productInfo']['price']=request.POST['maxPrice']
    request.session.modified = True
    product_list=sendingRequest(request,price_range=request.POST['maxPrice'], catergories= request.session['productInfo']['categories'], brand=request.session['productInfo']['brand'])
    return render(request,"ecommerce/product_list.html",{'product_list':product_list})
	
def searchProduct(request,category="shirt"):
    
    if request.method=='POST':
        request.session['productInfo']['categories']=request.POST['searchProduct']
        request.session.modified = True
        product_list=sendingRequest(request,catergories=request.POST['searchProduct'],brand=request.session['productInfo']['brand'])
    else:
        request.session['productInfo']['categories']=category
        request.session.modified = True
        product_list=sendingRequest(request,catergories=category,brand=request.session['productInfo']['brand'])
  
    
    return render(request,"ecommerce/product_list.html",{'product_list':product_list})
	
def searchBrand(request):

    request.session['productInfo']['brand']=request.POST['searchBrand']
    request.session.modified = True
    product_list=sendingRequest(request,brand=request.POST['searchBrand'],catergories= request.session['productInfo']['categories'],price_range=request.session['productInfo']['price'])
    
    return render(request,"ecommerce/product_list.html",{'product_list':product_list})



def sendingRequest(request,brand='nike',catergories="sport shirt",price_range=50,product_id=None):
    product_list=[]

    if product_id is not None:
        print("There is a product Id <<<<<<----------")
        query_params = {
            "q": "name:("+catergories+") brand:"+brand+" ",
            'size':'5'
        }
    else:
        print("Products more diverse, because, not requesting by product_id <<<<<<----------")
        query_params = {
            "q": "name:("+catergories+") price: <"+str(price_range)+" brand:"+brand+" ",
            "size":"25"
        }
    
    try:
        output = webhoseio.query("productFilter", query_params)
    except IndexError:
        print("Not found <<<<<<<<<<----------")

    for key,value in output.items():
        if key=='products':
            for index in value:
                if len(index['images'])<1:
                    continue
                else:
                    product_list.append(
                        {
                            'product_price':index['price'],
                            'product_image':index['images'][0],
                            'product_id':index['product_id'],
                            'product_brand':index['brand']
                        }
                    )
                
    # Get the next batch of products
    output = webhoseio.get_next()

    if len(product_list)<1:
    
        return HttpResponse("<h4 class='text-center text-white bg-dark p-3 mt-5 shadow'>Items Not Found!!</h4>")
    return (product_list)
    

Ecommerce/apps/dashboard/templates/ecommerce/checkout.html
{%extends 'ecommerce/layout.html'%}

{%block content%}
    <title>Checkout</title>
    {%load static%}
<div class="container">
    <div class="mb-3">
        {% if product_id not in request.session %}
            <a href="{%url 'dashboard:dashboard' %}" class="btn btn-primary">Back</a>
        {% else %}
            <a href="{%url 'dashboard:product_page' product_id=request.session.product_id product_brand=request.session.productInfo.brand%}" class="btn btn-primary">Back</a>
        {% endif %}
        
    </div>
    <div class="py-5 text-center">
        <img class="d-block mx-auto mb-4" src="{%static 'ecommerce/images/codingdojo.jpg'%}" alt="" width="72" height="72">
        <h2>Thanks for Shopping</h2>
        <p class="lead">Below is an example of a checkout form. Please do not put your real card information.This is just a personal project. So... it is a dummy form, with no validation</p>
    </div>
    
    <div class="row">
        <div class="col-md-4 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Your cart</span>
                <span class="badge badge-secondary badge-pill">{{totalItems}}</span>
            </h4>
            <ul class="list-group mb-3">
                
                {% for index in products %}
                    <li class="list-group-item d-flex justify-content-between lh-condensed">
                        <div class="">
                            <h6 class="my-0 font-weight-light">{{index.itemName}}</h6>
                        </div>
                        <span class="text-muted ml-5">${{index.price}}</span>
                    </li>
                {% endfor %}
                
                
                <li class="list-group-item d-flex justify-content-between bg-light">
                <div class="text-success">
                    <h6 class="my-0">Special Discount</h6>
                    <small>Happy Holiday</small>
                </div>
                <span class="text-success">-${{discount}}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                <span>Total (USD)</span>
                <strong>${{totalCost}}</strong>
                </li>
            </ul>

        </div>
        <div class="col-md-8 order-md-1">
        <h4 class="mb-3">Billing address</h4>
        <form action="{%url 'dashboard:payementProcess'%}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="firstName">First name</label>
                    <input type="text" class="form-control" id="firstName" name="firstName" placeholder="" >
                </div>
                <div class="col-md-6 mb-3">
                    <label for="lastName">Last name</label>
                    <input type="text" class="form-control" id="lastName" name="lastName" placeholder="" >
                </div>
            </div>

            <div class="mb-3">
                <label for="email">Email <span class="text-muted">(Required)</span></label>
                <input type="email" class="form-control" id="email" name="email" placeholder="you@example.com">
            </div>

            <div class="mb-3">
                <label for="address">Address</label>
                <input type="text" class="form-control" id="address" name="address" placeholder="1234 Main St" >
            </div>

            <div class="mb-3">
                <label for="address2">Address 2 <span class="text-muted">(Optional)</span></label>
                <input type="text" class="form-control" id="address2" name="address2" placeholder="Apartment or suite">
            </div>

            <div class="row">
                <div class="col-md-5 mb-3">
                    <label for="country">Country</label>
                    <input type="text" class="form-control" id="country" name="country" placeholder="country">

                </div>
                <div class="col-md-3 mb-3">
                    <label for="zip">Zip Code</label>
                    <input type="text" class="form-control" id="zip" name='zip' placeholder="" >
                    
                </div>
            </div>
            <hr class="mb-4">

            <h4 class="mb-3">Payment</h4>

            <div class="d-block my-3">
                <div class="custom-control custom-radio">
                    <input id="credit" name="paymentMethod" value="credit" type="radio" class="custom-control-input" checked >
                    <label class="custom-control-label" for="credit">Credit card</label>
                </div>
                <div class="custom-control custom-radio">
                    <input id="debit" name="paymentMethod" value="debit" type="radio" class="custom-control-input" >
                    <label class="custom-control-label" for="debit">Debit card</label>
                </div>
                <div class="custom-control custom-radio">
                    <input id="paypal" name="paymentMethod"  value="paypal" type="radio" class="custom-control-input" >
                    <label class="custom-control-label" for="paypal">PayPal</label>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="cc-name">Name on card</label>
                    <input type="text" class="form-control" id="cc-name" name="card_name" placeholder="" >
                    <small class="text-muted">Full name as displayed on card</small>
                    
                </div>
                <div class="col-md-6 mb-3">
                    <label for="cc-number">Credit card number</label>
                    <input type="text" class="form-control" id="cc-number" name="credit_card" placeholder="" >
                   
                </div>
            </div>
            <div class="row">
                <div class="col-md-3 mb-3">
                    <label for="cc-expiration">Expiration</label>
                    <input type="text" class="form-control" id="cc-expiration" name="expiration" placeholder="" >
                    
                </div>
                <div class="col-md-3 mb-3">
                    <label for="cc-cvv">CVV</label>
                    <input type="text" class="form-control" id="cc-cvv" name="cvv" placeholder="" >
                </div>
            </div>
            <hr class="mb-4">
            <input type="hidden" name="totalCost"  value="{{totalCost}}">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Checkout</button>
        </form>
        </div>
    </div>

    <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">&copy; 2017-2018 Company Name</p>
        <ul class="list-inline">
        <li class="list-inline-item"><a href="#">Privacy</a></li>
        <li class="list-inline-item"><a href="#">Terms</a></li>
        <li class="list-inline-item"><a href="#">Support</a></li>
        </ul>
    </footer>
</div>

  


{%endblock content%}

Ecommerce/apps/dashboard/templates/ecommerce/dashboard.html
{%extends "ecommerce/layout.html"%}

{%block head%}
    <title>Dashboard</title>

{%endblock head%}



{%block content%}
    <div class="col-12 text-right mb-4 ">
        <a  data-toggle="modal" data-target="#Cart" class="mr-2">
            <h6 class="d-inline badge badge-secondary badge-pill " id="itemAmount">{{itemsInCart}}</h6> <i class="fas fa-shopping-cart "></i>
        </a>
        <a href="{%url 'dashboard:checkout'%}" class="btn btn-success font-weight-light mr-3"> Proceed To Checkout</a>
    </div>
    <div class="row">
        <div class="leftsection col-3 bg-light pb-5">
            <form id="searchForm" action="{%url 'dashboard:searchProduct' category='shirt'%}" method="post">
                {% csrf_token %}
                <input class="mt-4" type="text" placeholder="Search" aria-label="Search" name="searchProduct" id="searchProduct">
                <button type="submit" value='Submit' class="btn btn-outline-primary btn-sm p-0 pt-1 pr-1 ml-2"><i class="fas fa-search ml-2"></i></button>
                
            </form>
            <h6 class="mt-3 bg-dark text-white p-2 mb-2">Catergories</h6>
            <ul>
                <li><a class="categoriesSearch" href="{%url 'dashboard:searchProduct' category='shirt'%}">T-shirts</a></li>
                <li><a class="categoriesSearch" href="{%url 'dashboard:searchProduct' category='shoes'%}">Shoes</a> </li>
                <li><a class="categoriesSearch" href="{%url 'dashboard:searchProduct' category='socks'%}">Socks</a></li>
                <li><a class="categoriesSearch" href="{%url 'dashboard:searchProduct' category='shorts'%}">Shorts</a></li>
                <li><a class="categoriesSearch" href="{%url 'dashboard:searchProduct' category='hoodie'%}">Hoodies</a></li>
            </ul>
            <hr>
            <h6 class="">Filters:</h6>
            <ul class="pl-1">
                <li>
                    <form action="{%url 'dashboard:PriceRange'%}" id="priceRangeForm" method="post">
                        {% csrf_token %}
                        <h6 class="font-weight-light">Price Range:</h6>
                        <p class="ml-2">Max: 
                            <input type="number" id="maxPrice" name="maxPrice" placeholder="$20"> 
                            <button type="submit" value='Submit' class="btn btn-outline-success btn-sm p-0 pt-1 pr-1 ml-2"><i class="fas fa-search-dollar"></i></button>
                        </p>
                        
                    </form>
                </li>
                <li>
                    <h6 class="font-weight-light">Brand Name:</h6>
                    <form id='SearchBrandForm' action="{%url 'dashboard:searchBrand'%}" method="post">
                        {% csrf_token %}
                        <p class="ml-2">Brand: <input type="text" id="brandName" name="searchBrand" placeholder="Nike"></p>
                        <button type="submit" value='Submit' class="btn btn-outline-primary btn-sm p-0 pt-1 pr-1 ml-2"><i class="fas fa-search ml-2"></i></button>
                    </form>
                </li>
                <li></li>
            </ul>
        
        </div>



        <div class="rightsection col-8 bg-light pb-5 ml-5">

            <div class="productPic">
                {% for index in product_list %}

                    <div class="box">
                    <a href="{%url 'dashboard:product_page' product_id=index.product_id product_brand=index.product_brand%}"> <img  class="product" src="{{index.product_image}}" alt="product image"></a>
                        <div class="overlay">
                            <div class="bg-dark shadow"><h5>${{index.product_price}}</h5></div>
                        </div>
                    </div>
                {% endfor %}

            </div>



        </div>
    </div>
    
   
    <script>
        $('#searchForm').submit(function(e) {
            e.preventDefault();
            console.log("search button clicked")

            $.ajax({
                method: "POST",
                url: $('#searchForm').attr('action'),
                data: $('#searchForm').serialize(),
                success: function(response){
                    console.log("response is: ", response)
                    $('.productPic').html(response)
                }
                });
            
                
        })
        
        $('.categoriesSearch').click(function() {
         
            console.log("categories button clicked")

            $.ajax({
                
                url: $(this).attr('href'),
                data: $('.categoriesSearch').serialize(),
                success: function(response){
                    console.log("response is: ", response)
                    $('.productPic').html(response)
                }
                });
            return false
                
        })

        $('#priceRangeForm').submit(function(e) {
            e.preventDefault();
            console.log("price range button clicked")

            $.ajax({
                method: "POST",
                url: $('#priceRangeForm').attr('action'),
                data: $('#priceRangeForm').serialize(),
                success: function(response){
                    console.log("response is: ", response)
                    $('.productPic').html(response)
                }
                });
            
                
        })
       
        $('#SearchBrandForm').submit(function(e) {
            e.preventDefault();
            console.log("brand search button clicked")

            $.ajax({
                method: "POST",
                url: $('#SearchBrandForm').attr('action'),
                data: $('#SearchBrandForm').serialize(),
                success: function(response){
                    console.log("response is: ", response)
                    $('.productPic').html(response)
                }
                });
            
                
        })

        
    </script>


{%endblock content%}

Ecommerce/apps/dashboard/templates/ecommerce/productPage.html
{%extends "ecommerce/layout.html"%}



{%block content%}

    <div class="container pb-5">
        <div class="row">
            <div class="text-left col-8">
                <i class="fas fa-arrow-alt-circle-left"></i>
                <a href="{%url 'dashboard:dashboard'%}"> Go Back</a>
            </div>
            <a class="col-4 text-right" data-toggle="modal" data-target="#Cart"><h6 class="d-inline badge badge-secondary badge-pill " id="itemAmount">{{itemsInCart}}</h6> <i class="fas fa-shopping-cart"></i></a>
        </div>

        <div class="row mt-5">
            <section class="col-4 productProfile">
                <h4>{{product_list.product_name}} <small class="font-weight-light"> by <a href="#">{{product_list.product_brand}}</a></small></h4>
                <hr>
                <img src="{{product_list.product_image}}" alt="product image">
                

            </section>

            <section class="col-7 ml-3 itemDescriptionSect">
                <h3 class="text-center font-weight-light">Item Description</h3>
                <hr>
                <div class="mb-5">
                    <h6 class="bg-dark p-3 text-white">Price: <span class="text-warning">${{product_list.product_price}}</span></h6>
                    <p class="font-weight-light mt-3 ml-3">{{product_list.product_description}}</p>
                    
                        
                </div>
                <div class="ml-2 mb-5">
                    <form id="addToCartForm" action="{%url 'dashboard:add_to_cart'%}" method="post">
                        {% csrf_token %}
                        <select name="quantity" class="ml-3">

                            <option value="1">1(${{product_list.product_price}})</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                
                        </select>
                        <input type="hidden" name="price" value="{{product_list.product_price}}">
                        <input type="hidden" name="brand" value="{{product_list.product_brand}}">
                        <input type="hidden" name="productName" value="{{product_list.product_name}}">
                        <button type="submit" class="btn btn-sm btn-dark ml-2">Add To Cart</button>
                            
                    </form>
                    
                </div>
                <hr>
                <h4>Customers who viewed this item also viewed</h4>

                <div class="SuggestedProductPic">
                    {% for index in suggested_product %}
                        <a href="{%url 'dashboard:product_page' product_id=index.product_id product_brand=index.product_brand%}" class="mr-2 "> <img  src="{{index.product_image}}" alt="product image" class="shadow mb-2"></a>
                    {% endfor %}
                </div>
                
            </section>
            <a href="{%url 'dashboard:checkout'%}" class="btn btn-success mt-5 d-block col-11 p-3 font-weight-light"> Proceed To Checkout</a>
            
        </div>
        <footer class="text-center bg-light p-3 col-11 mt-5">
            <p>MAAD &copy; 2018</p>
        </footer>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="Cart" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header ">
                    <div class="modalHeader text-center">
                        <h5>Cart Items</h5>
                    </div>
                    <button type="button" class="close closebutton ml-1" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="">

                        <p>Items In Cart display here!!</p>
                    </div>
                    
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success" data-dismiss="modal">Continue Shopping</button>
                </div>
                

            </div>
        </div>
    </div>
    <script>
        $("#addToCartForm").submit(function(e){
            e.preventDefault();
            console.log("add to cart button clicked")

            $.ajax({
                method: "POST",
                url: $('#addToCartForm').attr('action'),
                data: $('#addToCartForm').serialize(),
                success: function(response){
                    console.log("response is: ", response['numberOfItems'])
                    $('#itemAmount').html(response['numberOfItems'])
                }
                });
            
        })
    </script>

{%endblock content%}

Ecommerce/apps/dashboard/templates/ecommerce/product_list.html
{% for index in product_list %}

    <div class="box">
        <a href="{%url 'dashboard:product_page' product_id=index.product_id product_brand=index.product_brand%}"> <img  class="product" src="{{index.product_image}}" alt="product image"></a>
        <div class="overlay">
            <div class="bg-dark shadow"><h5>${{index.product_price}}</h5></div>
        </div>
    </div>
{% endfor %}