User_dashboard/User_dashboard/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^wall/',include('apps.MessageWall.urls', namespace='wall')),
    url(r'^dashboard/',include('apps.Dashboard.urls', namespace='dashboard')),
    url(r'^',include('apps.LoginAndRegister.urls', namespace='userLG'))
   
    

]

User_dashboard/apps/Dashboard/urls.py
from django.conf.urls import url
from .import views


urlpatterns=[
    url(r'^admin/$',views.Dashboard,name="Dashboard"),
    url(r'^admin/editUser/(?P<user_id>\d+)$',views.editUser,name="editUser"),
    url(r'^admin/addUser/$',views.addUser,name="addUser"),
    url(r'^update/(?P<user_id>\d+)$',views.update,name="update"),
    url(r'^destroy/$',views.destroy,name="destroy"),


]

User_dashboard/apps/LoginAndRegister/urls.py
from django.conf.urls import url
from .import views


urlpatterns=[
    url(r'^$',views.home,name='home'),
    url(r'^register/$',views.register,name='registration'),
    url(r'^create/$',views.create,name='create'),
    url(r'^login/$',views.login,name='login'),
    url(r'^loginProccess',views.proccess,name='proccess'),
    url(r'^logoff',views.logoff,name='logoff')


]

User_dashboard/apps/MessageWall/urls.py
from django.conf.urls import url

from .import views

urlpatterns=[
    url(r'^profile/(?P<currentPage>\d+)$',views.index,name='index'),
    url(r'^create/(?P<currentPage>\d+)$',views.create,name='create'),
    url(r'^createComment/(?P<post_id>\d+)/(?P<currentPage>\d+)$',views.createComment,name='createComment'),
    url(r'^destroy/(?P<user_id>\d+)/(?P<currentPage>\d+)$',views.destroy,name='destroy')
]

User_dashboard/apps/Dashboard/models.py
from django.db import models

# Create your models here.

User_dashboard/apps/Dashboard/views.py
from django.shortcuts import render,redirect
from django.core.urlresolvers import reverse
from django.contrib import messages

from ..LoginAndRegister.models import User

def Dashboard(request):
    if 'user_id' not in request.session:
        return redirect(reverse("userLG:login"))

    context={
        'all_user':User.objects.all,
        'user':User.objects.get(id=request.session["user_id"])
    }

    # checking if user is an admin or a normal user, and render the appropriate HTML
    if User.objects.get(id=request.session["user_id"]).user_level==0:
        return render(request,"dashboard/UserDashboard.html",context)

    elif User.objects.get(id=request.session["user_id"]).user_level==1:
        return render(request,"dashboard/AdminDashboard.html",context)

def editUser(request,user_id):
    if 'user_id' not in request.session:
        return redirect(reverse("userLG:login"))
    if User.objects.get(id=request.session["user_id"]).user_level==0:
        return redirect(reverse("userLG:login"))
    
    context={
        "user":User.objects.get(id=user_id)    
    }

    return render(request,"dashboard/AdminUserEdit.html",context)




def addUser(request):
    return render(request,"dashboard/newUser.html")



def update(request,user_id):

    valid,response=User.objects.EditUser(request.POST,user_id)

    if valid==False:

        for error in response:
            messages.error(request, error)

        # we can put the hidden value in the modal edit form so we can say if the value in the hidden form is "fromUser" redirect to the profile of the user.
        if request.POST["editRequest"]=="fromUser":
            return redirect(reverse('wall:index',kwargs={'currentPage': user_id }))

        return redirect(reverse("dashboard:editUser",kwargs={'user_id': user_id }))

    # If the FORM values has no errors , we can update the values......
    else:
        EditUser=User.objects.get(id=user_id)

        for key,value in request.POST.items():

            if value=="" or value=="-1" or key=="csrfmiddlewaretoken":
                continue
                
            else:
                if key=="first_name":
                    EditUser.first_name=request.POST[key]
                    EditUser.save()
                elif key=="last_name":
                    EditUser.last_name=request.POST[key]
                    EditUser.save()

                elif key=="email":
                    EditUser.email=request.POST[key]
                    EditUser.save()

                elif key=="user_level":
                    EditUser.user_level=request.POST[key]
                    EditUser.save()

                elif key=="description":
                    EditUser.description=request.POST[key]
                    EditUser.save()
   

    if request.POST["editRequest"]=="fromUser":
        return redirect(reverse('wall:index',kwargs={'currentPage': user_id }))

    return redirect(reverse("dashboard:editUser",kwargs={'user_id': user_id }))


def destroy(request):
    User.objects.get(id=request.POST["user"]).delete()
    return redirect(reverse("dashboard:Dashboard"))

User_dashboard/apps/Dashboard/templates/dashboard/AdminDashboard.html
<title>Dashboard</title>
{%extends "dashboard/dashLayout.html"%}

{%block content%}
    
    {% load static %}
    <script src="{%static 'dashboard/script/jquery.js' %}"></script>
    <div class="container">
        {% if messages %}
            <ul class=" list-inline messages text-success mt-4 ml-3 font-weight-light">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
    
        <h4 class="mt-5 col-3 d-inline-block subTitle "> <i class="fas fa-users"></i> Manage Users</h4>
        <div class="d-inline-block col-8 text-right ml-5">
            <a href="{%url 'dashboard:addUser'%}" class="btn btn-success shadow adduser">Add new User <i class="fas fa-user-plus"></i></a>
        </div>
        <table class="table table-hover table-striped table-dark mt-3 text-center">
            <thead class="thead-dark ">
                <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">User_level</th>
                <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {%for index in all_user%}

                    <tr>
                        <th scope="row">{{index.id}}</th>
                        <td><a href="{%url 'wall:index' currentPage=index.id%}">{{index.first_name}} {{index.last_name}}</a></td>
                        <td>{{index.email}}</td>
                        {%ifequal index.user_level 1%}
                            <td class="text-success">Admin</td>
                        {%else%}
                            <td>Normal User</td>
                        {%endifequal%}
                        <td class="actionbutton">
                            <!-- User edit Button -->
                            <a href="{%url 'dashboard:editUser' user_id=index.id%}" class="btn btn-warning"><i class="fas fa-user-edit"></i></a>

                            <!-- User Delete Button -->
                            <button data-userid='{{index.id}}' class="btn btn-danger ml-2" data-toggle="modal" data-target="#Delete"><i class="fas fa-user-times"></i></button>
                        </td>
                    
                    </tr>

                {%endfor%}

            </tbody>
        </table>

        <!-- Modal -->
        <div class="modal fade" id="Delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">

                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Delete Confirmation</h5>
                        
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form action="{%url 'dashboard:destroy'%}" method=post>
                        {% csrf_token %}
                        <div class="modal-body">
                            <p>Are you sure you want to delete this user?</p>
                            <input type="hidden" name="user" id="user_id" value="">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-danger">Yes, Delete User</button>
                        </div>
                    </form>
            </div>
            </div>
        </div>
    </div>


{%endblock content%}

User_dashboard/apps/Dashboard/templates/dashboard/AdminUserEdit.html
<title>Edit User</title>
{%extends "dashboard/dashLayout.html"%}


{% block content %}
    <div class="container">
        <h3 class="mt-4 d-inline-block col-6"> <i class="fas fa-user-edit mr-2"></i><small>{{user.first_name}} {{user.last_name}}</small></h3>
        <div class="col-5 d-inline-block text-right ml-4"><a href="{%url 'dashboard:Dashboard'%}" class=" btn btn-primary shadow"> Return to Dashboard</a></div>
    
        {% if messages %}
            <ul class=" list-inline messages text-danger">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
        <div class="row">
            <div class="leftsection col-6">
                <div class="mt-4">
                    <h6 class="mb-3 bg-dark text-white p-2 shadow">Edit Information</h6>


                    <form class="needs-validation" action="{%url 'dashboard:update' user_id=user.id%}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="firstName">First name</label>
                                <input type="text" class="form-control " id="firstName" name="first_name" value="" placeholder="{{user.first_name}}...">
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="lastName">Last name</label>
                                <input type="text" class="form-control" id="lastName" name="last_name" placeholder="{{user.last_name}}..">

                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="email">Email</label>
                            <input type="text" class="form-control" name="email" id="email" placeholder="you@example.com">
                        </div>
                        <div class="mb-3">
                                <label for="user_level">User Level</label>
                                <select class="custom-select" id="user_level" name="user_level">
                                    <option selected value="-1">Choose...</option>
                                    <option value="0">Normal</option>
                                    <option value="1">Admin</option>
                                </select>
                        </div>
                        <input type="hidden" name="editRequest" id="user_id" value="fromAdmin">
                        <hr class="mb-4">
                        <div class="text-right">
                            <button class="btn btn-success shadow" type="submit">Save</button>
                        </div>
                    </form>
                </div>


            </div>
            <div class="rightsection col-5 mt-4 ml-3">
                
                <h6 class=" mb-3 bg-dark text-white p-2 shadow">Change Password</h6>
                <form class="needs-validation" action="{%url 'dashboard:update' user_id=user.id%}" method="post">
                    {% csrf_token %}

                    <div class="mb-3 ">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" name="password" id="password" placeholder="password">

                    </div>
                    <div class="mb-3">
                        <label for="confirmPassword">Confirm Password</label>
                        <input type="password" class="form-control" name="confirmpassword" id="confirmPassword" placeholder="confirm password">
                    </div>
                    <input type="hidden" name="editRequest" id="user_id" value="fromAdmin">
                    <hr class="mb-4">
                    <div class="text-right">
                        <button class="btn btn-success shadow" type="submit">Update Password</button>
                    </div>

                </form>
                
                
            </div>
        </div>
    </div>
{% endblock %}

User_dashboard/apps/Dashboard/templates/dashboard/UserDashboard.html
<title>Dashboard</title>
{%extends "dashboard/dashLayout.html"%}

{%block content%}
    <div class="container">
        <h2 class="font-weight-light mt-4 text-center"> Hello <small class="font-weight-light">{{user.first_name}} !!</small></h2>
        {% if messages %}
            <ul class=" list-inline messages text-success">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <h4 class="mt-5 col-3 d-inline-block subTitle"> <i class="fas fa-users"></i> All Users</h4>

        <table class="table table-hover table-striped  mt-3 text-center">
            <thead class="thead-light ">
                <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Created_at</th>
                <th scope="col">User_level</th>
                
                </tr>
            </thead>
            <tbody>
                {%for index in all_user%}

                    <tr>
                        <th scope="row">{{index.id}}</th>
                        <td><a href="{%url 'wall:index' currentPage=index.id%}">{{index.first_name}} {{index.last_name}}</a></td>
                        <td>{{index.email}}</td>
                        <td>{{index.created_at}}</td>
                        {%ifequal index.user_level 1%}
                            <td class="text-success">Admin</td>
                        {%else%}
                            <td>Normal User</td>
                        {%endifequal%}
                    
                    </tr>

                {%endfor%}

            </tbody>
        </table>


    </div>


{%endblock content%}

User_dashboard/apps/Dashboard/templates/dashboard/dashLayout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>DashBoard_Layout</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    {%load static%}
    <link rel="stylesheet" href="{%static 'dashboard/css/stylesheet.css'%}">
    {%block head%}{%endblock%}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
   

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark pb-2">
        <div class="col-4">
            <a class="navbar-brand" href="{%url 'dashboard:Dashboard'%}">Coding Dojo</a>
            <a class="blog-header-logo text-white" href="{%url 'dashboard:Dashboard'%}">Dashboard</a>
            <a class="text-white ml-2" href="{%url 'wall:index' currentPage=request.session.user_id%}"> Profile</a>
        </div>
        <div class="col-8 text-right">
            <a class="text-white" href="{%url 'userLG:logoff'%}"> Log off  <i class=" ml-1 mr-2 fas fa-sign-out-alt"></i></a>
        </div>
    </nav>  

    {% block content %}{% endblock %}




    
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/scrollreveal"></script>
    <script>
        window.sr=ScrollReveal();

        sr.reveal('.subTitle,.adduser,.table', {
            duration:2000,
            scale:0.85
        });
        sr.reveal('.profileDesc', {
            duration:2000,
            origin:'top',
            distance:'300px',
            delay:'500'
        });
        sr.reveal('.profilepic', {
            duration:2000,
            scale:0.85
        });

    </script>
</body>
</html>

User_dashboard/apps/Dashboard/templates/dashboard/newUser.html
<title>Create User</title>
{%extends "dashboard/dashLayout.html"%}
{%load static%}
{%block content%}


<div class="container createUserContainer">

        <div class="py-5 text-center">
            <img class="d-block mx-auto mb-4" src="{%static 'logAndreg/image/codingdojo.jpg'%}" alt="" width="100" height="100">
            <h2>Create New User</h2>
            <p class="lead">Same validation rule applies</p>
        </div>


        <div class=" order-md-1 formss">
            {% if messages %}
                <ul class=" list-inline messages text-danger">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
                </ul>
            {% endif %}
            <h4 class="mb-3">User Information</h4>
            
            <form class="needs-validation" action="{%url 'userLG:create'%}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="firstName">First name</label>
                        {%if request.session.tempUserData.firstname%}
                            <input type="text" class="form-control " id="firstName" name="firstname" value={{request.session.tempUserData.firstname}}>

                        {%else%}
                            <input type="text" class="form-control " id="firstName" name="firstname" value="" placeholder="Enter first name">
                        {%endif%}
    
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="lastName">Last name</label>
                        {%if request.session.tempUserData.lastname%}
                            <input type="text" class="form-control" id="lastName" name="lastname" value={{request.session.tempUserData.lastname}}>

                        {%else%}
                            <input type="text" class="form-control" id="lastName" name="lastname" placeholder="Enter last name">
                        {%endif%}

                    </div>
                </div>
                <div class="mb-3">
                    <label for="email">Email</label>

                    {%if request.session.tempUserData.email%}
                        <input type="text" class="form-control" name="email" id="email" value={{request.session.tempUserData.email}} placeholder="you@example.com">

                    {%else%}
                        <input type="text" class="form-control" name="email" id="email" placeholder="you@example.com">
                    {%endif%}

                    
                </div>

                <div class="mb-3">
                    <label for="birthday">Birthday</label>
                    <input type="date" id="birthday" name="birthday"  class="form-control" value="" min="2018-01-01" max="2018-12-31" placeholder="Birthday: YYYY-MM-DD" />
                </div>

                <div class="mb-3">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" name="password" id="password" placeholder="password">

                </div>
                <div class="mb-3">
                    <label for="confirmPassword">Confirm Password</label>
                    <input type="password" class="form-control" name="confirmpassword" id="confirmPassword" placeholder="confirm password">
                </div>

                <hr class="mb-4">
                <button class="btn btn-success btn-lg btn-block shadow" type="submit">Create User</button>

            </form>
        </div>
    </div>



{%endblock content%}