User_dashboard/User_dashboard/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^wall/',include('apps.MessageWall.urls', namespace='wall')),
    url(r'^dashboard/',include('apps.Dashboard.urls', namespace='dashboard')),
    url(r'^',include('apps.LoginAndRegister.urls', namespace='userLG'))
   
    

]

User_dashboard/apps/Dashboard/urls.py
from django.conf.urls import url
from .import views


urlpatterns=[
    url(r'^admin/$',views.Dashboard,name="Dashboard"),
    url(r'^admin/editUser/(?P<user_id>\d+)$',views.editUser,name="editUser"),
    url(r'^admin/addUser/$',views.addUser,name="addUser"),
    url(r'^update/(?P<user_id>\d+)$',views.update,name="update"),
    url(r'^destroy/$',views.destroy,name="destroy"),


]

User_dashboard/apps/MessageWall/urls.py
from django.conf.urls import url

from .import views

urlpatterns=[
    url(r'^profile/(?P<currentPage>\d+)$',views.index,name='index'),
    url(r'^create/(?P<currentPage>\d+)$',views.create,name='create'),
    url(r'^createComment/(?P<post_id>\d+)/(?P<currentPage>\d+)$',views.createComment,name='createComment'),
    url(r'^destroy/(?P<user_id>\d+)/(?P<currentPage>\d+)$',views.destroy,name='destroy')
]

User_dashboard/apps/MessageWall/models.py
from __future__ import unicode_literals

from django.db import models
from ..LoginAndRegister.models import User
# Create your models here.

class Post(models.Model):
    content=models.TextField()
    user=models.ForeignKey(User,related_name='posts')
    recipient=models.ForeignKey(User,related_name="recipientPost")
    deleteButton=models.CharField(max_length=40)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

class Comment(models.Model):
    comment=models.TextField()
    post=models.ForeignKey(Post,related_name='comments')
    user=models.ForeignKey(User,related_name='comments')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

User_dashboard/apps/MessageWall/views.py
from django.shortcuts import render,redirect
from django.core.urlresolvers import reverse
from django.contrib import messages

from .models import Post,Comment
from ..LoginAndRegister.models import User

# import datetime
from datetime import timedelta,timezone,datetime
import time

def index(request,currentPage):

    # checking if there a user_id in session
    if 'user_id' not in request.session:
        return redirect(reverse("userLG:login"))

    # getting current user info
    current_user=User.objects.get(id=currentPage)

    # checking if to display the delete button in the post
    DeletePost= Post.objects.filter(deleteButton="null")
    for index in DeletePost:
        postTime=index.created_at
        dateNow=datetime.now().replace(tzinfo=timezone(-timedelta(hours=7)))
        minutes_elapsed = (dateNow - postTime).seconds/60

        if minutes_elapsed<30:
            index.deleteButton="display:inline-block"
        else:
            index.deleteButton="display:none"
        index.save()
            
    context={
        'user': current_user,
        'post':Post.objects.filter(recipient_id=currentPage).order_by("-created_at")
    }
    return render(request,'message/wall.html',context)

def create(request,currentPage):
    if 'user_id' not in request.session:
        return redirect(reverse("userLG:login"))

    # post validation
    if len(request.POST['post'])<3:
        messages.error(request, "Post should atleast be 3 characters")
        return redirect(reverse('wall:index',kwargs={'currentPage': currentPage }))
        
    # create the post
    Post.objects.create(content=request.POST['post'],deleteButton="null",recipient=User.objects.get(id=currentPage), user=User.objects.get(id=request.session['user_id']))
    return redirect(reverse('wall:index',kwargs={'currentPage': currentPage }))


def createComment(request,post_id,currentPage):
    if 'user_id' not in request.session:
        return redirect(reverse("userLG:login"))

    # comment validation
    error=[]
    if len(request.POST['comment'])<3:
        error.append("comment should atleast be 3 characters")
        messages.error(request, error)
        return redirect(reverse('wall:index',kwargs={'currentPage': currentPage }))

    # create the comment
    Comment.objects.create(comment=request.POST['comment'],post=Post.objects.get(id=post_id), user=User.objects.get(id=request.session['user_id']))
    return redirect(reverse('wall:index',kwargs={'currentPage': currentPage }))

def destroy(request,user_id,currentPage):

    # checking if there is user_id in session
    if 'user_id' not in request.session:
        return redirect(reverse("userLG:login"))

    # checking if the post is for the user and if yes, delete the post
    if request.session['user_id']==int(user_id):
        Post.objects.get(id=request.POST['post_id']).delete()

    return redirect(reverse('wall:index',kwargs={'currentPage': currentPage }))

User_dashboard/apps/MessageWall/templates/message/wall.html
<title>Pofile</title>
{%extends "dashboard/dashLayout.html"%}


{% block content %}
    {% load static %}
    <script src="{%static 'message/script/jquery.js' %}"></script>
    <link rel="stylesheet" href="{%static 'message/css/stylesheet.css'%}">

    <div class="container bg-light mt-4">
        <div class="py-5 text-center background text-white " style="background-image: url('{%static "message/image/profileBG.jpg"%}');">
            <div class="row profileHeader">
                <div class="col-2 profilepic">
                    <img class="d-block mx-auto mb-2 rounded-circle" src="{%static 'message/image/profilePic.jpg' %}" alt="profile pic" width="120" height="125">
                    
                    <small class="d-block"><i class="fas fa-birthday-cake "></i> {{user.birthday}}</small>
                    <small class="d-block ml-4 mt-2 emaildisplay"><i class="fas fa-at"></i> {{user.email}}</small>

                    <!-- User edit Button -->
                    {% ifequal user.id request.session.user_id %}
                        <button data-toggle="modal" data-target="#edit" class="btn btn-warning mt-3"><i class="fas fa-user-edit"></i></button>
                    {% endifequal %}

                </div>
                <div class="col-8 profileDesc">
                    <h2>{{user.first_name}} {{user.last_name}}</h2>
                    <hr>
                    <lead class="lead">{{user.description}}</lead>
                </div>
            </div>
            
        </div>
    
        {% if messages %}
            <ul class=" list-inline messages text-danger ml-3 mt-3">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }} ml-2"{% endif %}><small>{{message }}</small> </li>
                {% endfor %}
            </ul>
        {% endif %}

        <div class="mt-4 ml-4">
            <div class="form-group">
                <form action="{% url 'wall:create' currentPage=user.id%}" method="post">
                    {% csrf_token %}
                    <label for="post">Post a message</label>
                    <textarea class="form-control col-8" id="post" name="post" rows="5"></textarea>
                    <div class="row justify-content-end col-8"><button type="submit" class="btn btn-success mt-2 pl-4 pr-4">Post</button></div>
                </form>
            </div>
        </div>
        <div class="PostSection ml-4 ">
            {% for index in post %}
                {% comment %} Main Post {% endcomment %}
                <div class="mt-4">
                    <small class="font-weight-bold">{{index.user.first_name}} {{index.user.last_name}} - {{index.created_at}}</small>
                    <!-- delete Button functionality -->
                    <form action="{%url 'wall:destroy' user_id=index.user.id currentPage=user.id%}" method="post" class="d-inline-block">
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value="{{index.id}}">
                        <button type="submit" class="btn btn-sm btn-light pt-0 pb-0 text-danger" style="{{index.deleteButton}};">Delete</button>
                    </form>
                </div>
                <p class="ml-2 mb-0">{{index.content}}</p>
                <button class="viewButton btn btn-sm btn-light font-weight-light pt-0 pb-0">View Comments</button>
                <button class="viewPostElement btn btn-sm btn-light pt-0 pb-0">Reply</button>

                <div class="ml-4 mt-2 replies">
                   
                    <div>
                        {% for comment in index.comments.all %}
                            <div>
                                <small class="font-weight-light">{{comment.user.first_name}}{{comment.user.last_name}} - {{comment.created_at}}</small>
                                <p class="ml-1">{{comment.comment}}</p>
                            </div>
                        {% endfor %}
                    </div>
                </div>

                {% comment %} Post Button {% endcomment %}
                <form action="{% url 'wall:createComment' post_id=index.id currentPage=user.id%}" method="post" class="ml-3 mt-3 postCom">
                    {% csrf_token %}
                    <label class="font-weight-light" for="comment">Post a comment</label>
                    <textarea class="form-control col-5" id="comment" name="comment" rows="2"></textarea>
                    <div class="row justify-content-end col-5 ml-2"><button type="submit" class="btn btn-sm btn-primary mt-2 ">Comment</button></div>
                </form>

            {% endfor %}
        </div>
    
    </div>

    <!-- Modal -->
    <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header ">
                    <div class="modalHeader text-center">
                        <button class=" btn btn-light" id="editButton">Edit Information</button>
                        <button class=" btn btn-light ml-2" id="passswordButton">Change Password</button>
                    </div>
                    <button type="button" class="close closebutton ml-1" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div>
                        <div class="editInfoSection">
                            <h6 class="mb-3 bg-dark text-white p-2 shadow">Edit Information</h6>
                            <form class="needs-validation" action="{%url 'dashboard:update' user_id=user.id%}" method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-6 mb-3">
                                        <label for="firstName">First name</label>
                                        <input type="text" class="form-control " id="firstName" name="first_name" value="" placeholder="{{user.first_name}}...">
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        <label for="lastName">Last name</label>
                                        <input type="text" class="form-control" id="lastName" name="last_name" placeholder="{{user.last_name}}..">
            
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label for="email">Email</label>
                                    <input type="text" class="form-control" name="email" id="email" placeholder="you@example.com">
                                </div>
                                <div class="form-group">
                                    <label for="description">Description</label>
                                    <textarea class="form-control" name="description" id="description" rows="3"></textarea>
                                </div>

                                <hr class="mb-4">
                                <input type="hidden" name="editRequest" id="user_id" value="fromUser">
                                <div class="text-right">
                                    <button class="btn btn-success shadow" type="submit">Save</button>
                                </div>
                            </form>
                        </div>
                        <div class="editPasswordSection">
            
                            <h6 class=" mb-3 bg-dark text-white p-2 shadow">Change Password</h6>
                            <form class="needs-validation" action="{%url 'dashboard:update' user_id=user.id%}" method="post">
                                {% csrf_token %}
                
                                <div class="mb-3 ">
                                    <label for="password">Password</label>
                                    <input type="password" class="form-control" name="password" id="password" placeholder="password">
                
                                </div>
                                <div class="mb-3">
                                    <label for="confirmPassword">Confirm Password</label>
                                    <input type="password" class="form-control" name="confirmpassword" id="confirmPassword" placeholder="confirm password">
                                </div>
                                <input type="hidden" name="editRequest" id="user_id" value="fromUser">
                                <hr class="mb-4">
                                <div class="text-right">
                                    <button class="btn btn-success shadow" type="submit">Update Password</button>
                                </div>
                
                            </form>
                            
                                
                        </div>
                    </div>
                   
                    
      
                </div>

            </div>
        </div>
    </div>

{%endblock content%}